.github/workflows/auto-update-prs.yml
---
name: Auto-update PRs
on:
  push: { branches: [ main ] }
  schedule: [ { cron: "*/30 * * * *" } ]
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: write }
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner, repo: context.repo.repo, state: 'open'
            });
            for (const pr of prs) {
              if (pr.base.ref !== 'main') continue;
              await github.rest.pulls.updateBranch({
                owner: context.repo.owner, repo: context.repo.repo, pull_number: pr.number
              }).catch(e => core.warning(`PR #${pr.number}: ${e.message}`));
            }