name: Post Status Check

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to post status to'
        required: true
      pr_number:
        description: 'PR number'
        required: true

jobs:
  post-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - name: Post gate status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Post a success status for the gate check
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.inputs.sha }}',
              state: 'success',
              context: 'gate',
              description: 'Gate check passed',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${{ github.event.inputs.pr_number }}`
            });
            
            console.log('Successfully posted gate status check');